# Generated by Django 5.2 on 2025-05-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.theodysseyrestaurant.com%2F&psig=AOvVaw2gyu0awhbj5ADPjOBtjQAd&ust=1746486931934000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODI-v74io0DFQAAAAAdAAAAABAE')),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
