# Generated by Django 5.2 on 2025-05-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_veg', models.BooleanField(default=True)),
                ('picture', models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.theodysseyrestaurant.com%2F&psig=AOvVaw2gyu0awhbj5ADPjOBtjQAd&ust=1746486931934000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODI-v74io0DFQAAAAAdAAAAABAE')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
